// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tkacheva_lr2.Data;

#nullable disable

namespace tkacheva_lr2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AppUserRSSChannel", b =>
                {
                    b.Property<int>("SubscribedChannelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubscribersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubscribedChannelsId", "SubscribersId");

                    b.HasIndex("SubscribersId");

                    b.ToTable("UserChannelSubscriptions", (string)null);
                });

            modelBuilder.Entity("tkacheva_lr2.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "1234",
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("tkacheva_lr2.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RSSChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RSSChannelId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PublishedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RSSChannelId = 1,
                            Title = "Quantum mechanics",
                            Url = "https://example.com/qm"
                        },
                        new
                        {
                            Id = 2,
                            PublishedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RSSChannelId = 2,
                            Title = "Organic chemistry",
                            Url = "https://example.com/organic"
                        });
                });

            modelBuilder.Entity("tkacheva_lr2.Models.RSSChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RSSChannels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Physics articles",
                            Name = "Physics",
                            Url = ""
                        },
                        new
                        {
                            Id = 2,
                            Description = "Articles on chemistry",
                            Name = "Chemistry",
                            Url = ""
                        });
                });

            modelBuilder.Entity("AppUserRSSChannel", b =>
                {
                    b.HasOne("tkacheva_lr2.Models.RSSChannel", null)
                        .WithMany()
                        .HasForeignKey("SubscribedChannelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tkacheva_lr2.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("SubscribersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tkacheva_lr2.Models.Article", b =>
                {
                    b.HasOne("tkacheva_lr2.Models.RSSChannel", "RSSChannel")
                        .WithMany("Articles")
                        .HasForeignKey("RSSChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RSSChannel");
                });

            modelBuilder.Entity("tkacheva_lr2.Models.RSSChannel", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
